[tool.poetry]
name = "uhi"
version = "0.1.0"
description = "Unified Histogram Indexing"
authors = ["Henry Schreiner <henryschreineriii@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
typing_extensions = { version = "^3.7", python = "<3.8" }

sphinx = {version = "3", optional = true}
sphinx-rtd-theme = { version = "^0.5.1", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-rtd-theme"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
